# Generated by Django 3.1.3 on 2021-03-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('avg_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chain_comparison', models.CharField(max_length=20)),
                ('year_on_year', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'house_price_202102',
            },
        ),
    ]
