# Generated by Django 3.1.3 on 2021-03-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotNovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('status', models.CharField(default=None, max_length=100)),
                ('update', models.DateField(default=None)),
                ('length', models.IntegerField(default=0)),
                ('cover', models.URLField(default='http://www.wenku8.net/index.php')),
            ],
            options={
                'db_table': 'hot_novel',
            },
        ),
    ]
