# Generated by Django 3.1.3 on 2021-05-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelRecord',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'novel_record',
            },
        ),
        migrations.CreateModel(
            name='UserOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('read', models.IntegerField(default=0)),
                ('collection', models.IntegerField(choices=[(0, '收藏'), (1, '没有收藏')], default=0)),
                ('comment', models.CharField(default=None, max_length=10000, null=True)),
                ('download', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_operation',
            },
        ),
    ]
