# Generated by Django 3.1.3 on 2021-05-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0002_novelrecord_useroperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroperation',
            name='collection',
            field=models.IntegerField(choices=[(0, '收藏'), (1, '没有收藏')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='useroperation',
            name='download',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='useroperation',
            name='read',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
