# Generated by Django 3.1.3 on 2021-05-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0003_auto_20210525_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NovelRecord',
        ),
        migrations.AddField(
            model_name='useroperation',
            name='novel_id',
            field=models.IntegerField(default=None),
        ),
    ]
