# Generated by Django 3.1.3 on 2021-05-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0004_auto_20210525_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroperation',
            name='collection',
            field=models.IntegerField(choices=[(1, '收藏'), (0, '没有收藏')], default=0, null=True),
        ),
    ]
