# Generated by Django 3.1.3 on 2021-05-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0005_auto_20210525_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotnovel',
            name='download',
            field=models.URLField(default='http://www.wenku8.net/index.php'),
        ),
        migrations.AddField(
            model_name='hotnovel',
            name='read',
            field=models.URLField(default='http://www.wenku8.net/index.php'),
        ),
    ]
