# Generated by Django 3.1.3 on 2021-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2000-1-1', max_length=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('net_chg_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('symbol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'foreign_currency',
            },
        ),
    ]
