# Generated by Django 3.1.3 on 2021-04-08 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie2011',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2011',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2012',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2012',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2013',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2013',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2014',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2014',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2015',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2015',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2016',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2016',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2017',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2017',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2018',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2018',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2019',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2019',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2020',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2020',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='Movie2021',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_2021',
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='MovieWhole',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.movie')),
            ],
            options={
                'db_table': 'movie_whole',
            },
            bases=('movie.movie',),
        ),
    ]
