# Generated by Django 3.1.3 on 2021-04-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2011',
            },
        ),
        migrations.CreateModel(
            name='Movie2012',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2012',
            },
        ),
        migrations.CreateModel(
            name='Movie2013',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2013',
            },
        ),
        migrations.CreateModel(
            name='Movie2014',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2014',
            },
        ),
        migrations.CreateModel(
            name='Movie2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2015',
            },
        ),
        migrations.CreateModel(
            name='Movie2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2016',
            },
        ),
        migrations.CreateModel(
            name='Movie2017',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2017',
            },
        ),
        migrations.CreateModel(
            name='Movie2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2018',
            },
        ),
        migrations.CreateModel(
            name='Movie2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2019',
            },
        ),
        migrations.CreateModel(
            name='Movie2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2020',
            },
        ),
        migrations.CreateModel(
            name='Movie2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_2021',
            },
        ),
        migrations.CreateModel(
            name='MovieWhole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie_whole',
            },
        ),
    ]
