# Generated by Django 3.1.3 on 2021-03-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('box', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_avg_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_players', models.DecimalField(decimal_places=0, max_digits=5)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'movie2011',
            },
        ),
    ]
