# Generated by Django 3.1.3 on 2021-03-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie2011',
            table='movie_2011',
        ),
    ]
