# Generated by Django 3.1.3 on 2021-05-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('cover', models.URLField(default='https://www.dushu.com/book/1175_1.html')),
                ('author', models.CharField(default=None, max_length=100)),
                ('publisher', models.CharField(default=None, max_length=100)),
                ('isbn', models.CharField(default=None, max_length=100)),
                ('time', models.DateField(default='2021-05-18', max_length=20)),
                ('pack', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
