# Generated by Django 3.1.3 on 2021-05-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default='https://www.dushu.com/book/13802642/'),
        ),
    ]
