# Generated by Django 3.1.3 on 2021-05-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'CAR',
            },
        ),
        migrations.CreateModel(
            name='DANCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'DANCE',
            },
        ),
        migrations.CreateModel(
            name='DIGITAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'DIGITAL',
            },
        ),
        migrations.CreateModel(
            name='ENTERTAINMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'ENTERTAINMENT',
            },
        ),
        migrations.CreateModel(
            name='FOOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'FOOD',
            },
        ),
        migrations.CreateModel(
            name='GAME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'GAME',
            },
        ),
        migrations.CreateModel(
            name='KNOWLEDGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'KNOWLEDGE',
            },
        ),
        migrations.CreateModel(
            name='LIFE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'LIFE',
            },
        ),
        migrations.CreateModel(
            name='MOVIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'MOVIES',
            },
        ),
        migrations.CreateModel(
            name='MUSIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'MUSIC',
            },
        ),
        migrations.CreateModel(
            name='ZOO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('author', models.CharField(default=None, max_length=100)),
                ('pubdate', models.CharField(default=None, max_length=100)),
                ('play_volume', models.FloatField()),
                ('barrage', models.CharField(default=None, max_length=100)),
                ('classification', models.CharField(default=None, max_length=100)),
                ('likes', models.CharField(default=None, max_length=100)),
                ('coins', models.CharField(default=None, max_length=100)),
                ('collect', models.CharField(default=None, max_length=100)),
                ('share', models.CharField(default=None, max_length=100)),
                ('url', models.URLField(default='https://www.bilibili.com/')),
            ],
            options={
                'db_table': 'ZOO',
            },
        ),
    ]
